### ISSUE TITLE
Translate yaml / properties files 

### ISSUE THREAD

**Issue by kamilbeben** [funkyremi/vscode-google-translate#80]
Hi, many popular frameworks handles i18n using .yaml, or .properties files.
It would be handy to be able to translate whole file at once (excluding i18n keys of course).

Example
From
```yaml
production-order:
  view-name: Production order
  editor-field:
    completion-term: Completion term
```
```properties
production-order.view-name=Production order
production-order.editor-field.completion-term=Completion term
```
To
```yaml
production-order:
  view-name: Zlecenie produkcyjne
  editor-field:
    completion-term: Termin realizacji
```
```properties
production-order.view-name=Zlecenie produkcyjne
production-order.editor-field.completion-term=Termin realizacji
```

If you're on board with this feature i've forked your project and created a [pull request](https://github.com/funkyremi/vscode-google-translate/pull/79/files).
